@verse.Mesh.Net.ShippingService_HostAddress = http://localhost:5220

GET {{verse.Mesh.Net.ShippingService_HostAddress}}/health/
Accept: application/json

###

GET {{verse.Mesh.Net.ShippingService_HostAddress}}/c56a4180-65aa-42ec-a945-5fd21dec0538
Accept: application/json

###
