@verse.Mesh.Net.CartService_HostAddress = http://localhost:5049

GET {{verse.Mesh.Net.CartService_HostAddress}}/health/
Accept: application/json

###

GET {{verse.Mesh.Net.CartService_HostAddress}}/c56a4180-65aa-42ec-a945-5fd21dec0538
Accept: application/json

###
